export const JOBS_RECEIVED = "JOBS_RECEIVED";
export const ONCHANGE_SKILLS = "ONCHANGE_SKILLS";
export const ONCHANGE_ALLSKILLS = "ONCHANGE_ALLSKILLS";
export const ONCHANGE_JOBLOCATION = "ONCHANGE_JOBLOCATION";
export const ONCHANGE_USERLOCATION = "ONCHANGE_USERLOCATION";
export const GET_FILTERS = "GET_FILTERS";
export const JOB_RECEIVED = "JOB_RECEIVED";
export const SAVEDJOBS_RECEIVED = "SAVEDJOBS_RECEIVED";
