apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: bc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bc
  template:
    metadata:
      labels:
        app: bc
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image1.repository }}:{{ .Values.image1.tag }}"
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: bc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bc
  template:
    metadata:
      labels:
        app: bc
    spec:
      containers:
      - name: db
        image: "{{ .Values.image2.repository }}:{{ .Values.image2.tag }}"
        env:
          - name: POSTGRES_USER
            value: {{ .Values.secert1.Postgres_user }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.secert1.Postgres_passwd }} 
          - name: POSTGRES_DB
            value: {{ .Values.secert1.Postgres_db }}
        ports:
          - name: http
            containerPort: 5432
            protocol: TCP
       
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: bc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bc
  template:
    metadata:
      labels:
        app: bc
    spec:
      containers:
      - name: backend
        image: "{{ .Values.image3.repository }}:{{ .Values.image3.tag }}"
        env:
          - name: SPRING_DATASOURCE_URL
            value: {{ .Values.secert2.jobs_url }}
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.secert2.jobs_usr }} 
          - name: SPRING_DATASOURCE_PASSWORD
            value: {{ .Values.secert2.jobs_passwd }}
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: {{ .Values.secert2.jobs_update }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP










       
