apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bc-15
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx 
  rules:
  - host: aaa35c5c1e575435399683d87c280d3e-43b2d8e917307fd9.elb.us-east-2.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myrelease-frontend
            port:
              number: 3000
 