apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bc-15
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx 
  rules:
  - host: a77aad84ffcc7497187beb6b5603b0b4-3edccc726192ad61.elb.us-east-2.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myrelease-frontend
            port:
              number: 3000
      # - path: /api/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: myrelease-backend
      #       port:
      #         number: 8080