apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx 
  rules:
  - host: a2d5a1f05897a4a428999311c3a29667-80dd796f381964d9.elb.us-east-2.amazonaws.com
    http:
      paths:
      - path: /api/jobs
        pathType: Prefix
        backend:
          service:
            name: httpd-service
            port:
              number: 80
      - path: /api/skills
        pathType: Prefix
        backend:
          service:
            name: nginx-service  
            port:
              number: 80